language: python
python:
  - "3.9"
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install BeautifulSoup4
  - pip install codecov
script:
  - python web_server_examples/hello_world/server_hello_world.py & APP_PID=$!
  - coverage run tests/web_server_examples/hello_world/*.*
  - kill $APP_ID
after_success:
  - codecov
